### ISSUE TITLE
[Suggestion] Strip HTML comments

### ISSUE THREAD

**Issue by mikehayesuk** [miickel/gulp-angular-templatecache#10]
It seems that HTML comments are retained. I can see why some people would wish to have these retained for Angular purposes. However for those of us who don't use HTML comments for anything but commenting, it would be nice to have these stripped out to minimise the output.

Thanks

**Comment by isometriq** [comment]
I had the same question and I understand now.

I used this module for minifying the html:
https://github.com/murphydanger/gulp-minify-html

It looks like this (just before the angularTemplateCache() pipe:

    var minifyHtml = require('gulp-minify-html');
    var angularTemplateCache = require('gulp-angular-templatecache');
    ...
    
    return gulp.src([baseDir + '/**/*.html'])
        .pipe(minifyHtml(minifyHtmlOptions))
        .pipe(angularTemplateCache(angularTemplateCacheOptions))
        .pipe(concat(outputFilename || 'templates.js'))
        .pipe(ngAnnotate())
        .pipe(gulpif(config.production, uglify()))
        .pipe(gulp.dest(outputFolder || elixir.config.js.outputFolder));

**Comment by isometriq** [comment]
I used html minification (above) with these options

    minifyHtmlOptions = {
        empty: true,
        loose: true
    }

**Comment by phazei** [comment]
Would be nice to have an example like this in the readme, just as a FYI, you can do this too.

**Comment by dmellstrom** [comment]
> Would be nice to have an example like this in the readme, just as a FYI, you can do this too.

While it might help some folks, comment removal is outside the scope of this plugin, so I don't think it belongs in the README. A simple web search should yield `gulp-htmlmin`, which is great for that purpose.
