### ISSUE TITLE
Seems to be randomly re-ordering templates and changing names

### ISSUE THREAD

**Issue by jakefoster** [miickel/gulp-angular-templatecache#104]
Re-running from unchanged source results in the following.  Notice both the re-ordering and the change in case from noteModal.tpl.html to NoteModal.tpl.html (the original is still called noteModal.tpl.html).  Is there any way to prevent this behavior and have the order (and names) be deterministic?

![image](https://cloud.githubusercontent.com/assets/1377898/10065369/a53c7f4e-6239-11e5-818b-59a222fa5eaa.png)

**Comment by miickel** [comment]
Did you not pipe your HTML through some other gulp plugin before this one, that might have caused this behaviour? As far as I can tell, the result of running this plugin should be deterministic... and definitely not change file names here and there. (please confirm if this is a bug)

**Comment by jakefoster** [comment]
After more research it looks like this is the result of an upstream plugin doing some weird stuff.  I don't think it's a bug.  Sorry for the false alarm!
