### ISSUE TITLE
Drop the path?

### ISSUE THREAD

**Issue by austinstudio** [miickel/gulp-angular-templatecache#105]
I am tying to drop the path to the files when I put them into the templatecache.  I have files within different sub-modules in the file system and I want to drop the path so that when they are referenced in templatecache they aren't referenced like the following:

    common/addBusiness/validateFein/selectTask.html
    common/layout/topNav.html

But in stead are referenced like the following:

    selectTask.html

Notice, I have files in different levels so I can't just do '../../' or something like that.  This plugin used to do this but I guess I updated or something and now it doesn't.  I have played around with the 'base' and 'root' attributes but haven't been able to figure it out.

**Comment by austinstudio** [comment]
I didn't really fix this but I did find a workable solution.  I used a flatten module in gulp to flatten the folder structure before piping it out to templatecache.  It would be nice to be able to set the path to nothing instead but for now this is working.  Any other suggestions would be appreciated.

**Comment by miickel** [comment]
I'm pretty sure this plugin has never done that. If you were happy using a previous version it's fully possible to go back and use it now as well (just set a fixed version number in your package.json).

Another option is to use `options.transformUrl`

**Comment by danielcrisp** [comment]
This works for me:

```javascript
var gulp = require('gulp');
var templateCache = require('gulp-angular-templatecache');

gulp.task('default', function () {
  return gulp.src('app/**/*.html')
    .pipe(templateCache('app.templates.js', {
        transformUrl: function (url) {
            var split = url.split('/');
            return split[split.length - 1];
        }
    }))
    .pipe(gulp.dest('.tmp'));
});
```

**Comment by austinstudio** [comment]
Awesome.  Thanks @danielcrisp.  That seems like a bit of a better solution than what I was doing by flattening the pipe.

**Comment by red2678** [comment]
:+1:  Thanks!

**Comment by Burnett01** [comment]
Great solution @danielcrisp 

I use ``path.sep`` in order to have it work on Windows:

```javascript
var path = require('path');
var gulp = require('gulp');
var templateCache = require('gulp-angular-templatecache');

gulp.task('default', function () {
  return gulp.src('app/**/*.html')
    .pipe(templateCache('app.templates.js', {
        transformUrl: function (url) {
            var split = url.split(path.sep);
            return split[split.length - 1];
        }
    }))
    .pipe(gulp.dest('.tmp'));
});
```
