### ISSUE TITLE
Extract template without html file

### ISSUE THREAD

**Issue by ghost** [miickel/gulp-angular-templatecache#106]
Hello, I have a question...in my project I have only templates generate with gulp-angular-templatecache. Now I want to modify this template and in this way is very difficult. Is there a way to extract the html? Thanks!

**Comment by miickel** [comment]
The output is just regular HTML escaped to work inside a JavaScript string. So remove the escape characters to turn it into regular HTML again. Your text editor should be able to do a find & replace
