### ISSUE TITLE
Enhance readme

### ISSUE THREAD

**Issue by derekhe** [miickel/gulp-angular-templatecache#110]
I faced one issue just follow your steps in readme. The problem is template module can't find. I was struggling for a long time then found a tutorial to make it really work.

http://paulsalaets.com/pre-caching-angular-templates-with-gulp/

I finally know what I need to give my app a dependency on to the module to make it work. So could you enchance your readme or link to this blog to give better guide?

**Comment by EvgeniyRRU** [comment]
According a readme.md, we can to define *module* option declare your Angular application name. Before now, it works fine for me. But I faced with similar problem. May be, it caused by incorrect using CoffeScript and ngClassify gulp plugin. I'm puzzling out it.

**Comment by miickel** [comment]
It's pretty standard AngularJs stuff, really... when you add a module you must reference it in your app before using it. This plugin generates nothing but a regular Angular module. You have to add a reference to it in order for Angular's dependency injection mechanism to work properly.

I'll see if I can make this clearer in the readme with an upcoming update. thx!
