### ISSUE TITLE
An option to use relative path instead of absolute by default

### ISSUE THREAD

**Issue by bistory** [miickel/gulp-angular-templatecache#117]
Hi,

I don't really understand why this module behaves this way by default but it should be good to use relative path instead of absolute...

At the moment, when I compile my templates, I get this kind of lines : 

`$templateCache.put("/Users/thomas/Projects/prime_dashboard/build/dev/modules/common/views/_selection.html", ...)`

it should be :

`$templateCache.put("modules/common/views/_selection.html", ...)`

For the moment, I have to make a replace to fix bad URL.

Please make it more straighforward :-)

**Comment by hungdoan2** [comment]
@bistory can you show me your `gulp.src()` & `templateCache()` configuration`

**Comment by forty8bits** [comment]
@bistory: I noticed this behaviour when I had set a different base when sourcing the files, e.g. `gulp.src('src/app/**/*.html', { base: 'src' })`. Removing this fixed the issue for me.

**Comment by bistory** [comment]
@forty8bits You are right, that was the cause of the issue, thank you !

**Comment by gittycat** [comment]
I just wasted quite a bit of time trying to figure this one out.
Yes, removing `{ base: 'wver' }` gets things working but it isn't a fix.
This Issue shouldn't be closed. It really looks like a bug in templatecache.

**Comment by mdsmith00** [comment]
In my case I was able to work around this issue by setting the absolute path of the base like so:
```javascript
var path = require('path');
...
gulp.src('src/app/**/*.html', { base: path.resolve('src/'})
```
Path is the NodeJS path module.

The reason I found that `{ base: 'src'}` did not work was that [this line](https://github.com/miickel/gulp-angular-templatecache/blob/v2.2.0/index.js#L65) simply replaced 'src' with '' in the absolute file path.

**Comment by Zelgadis87** [comment]
Thanks for the workaround @mdsmith00, worked perfectly.
I agree with the others here, it should be relative paths by default. Just wasted 30 minutes wondering why my build was not working..

**Comment by aliptay** [comment]
omg, I just spent 4 hours wondering why my build was not working after 2 years of working, thanks @mdsmith00 .

For me the symptom was in the minified js, the e.put was using /app/app.html but was being referenced elsewhere as app/app.html

This just started happening for me sometime since Dec 6th, 2017

**Comment by pos1tron** [comment]
Having a hard time getting mdsmith00's solution to work for me. All I need to do is remove the leading forward slash.

**Comment by mchapman** [comment]
I was in the same situation as @pos1tron and kludged it with

`.pipe(replace(/templateCache.put\('\//g, "templateCache.put('"))`

**Comment by simonua** [comment]
If anyone wanted to provide a non-breaking PR, I'd be happy to look at it.
