### ISSUE TITLE
Error: $injector:nomod Module Unavailable

### ISSUE THREAD

**Issue by drmule** [miickel/gulp-angular-templatecache#119]
Your templates module is missing the empty array. Bug resolved once I manually added this.
Error: angular.module("templates").run([$templateCache,
Works: angular.module("templates", []).run([$templateCache,

From Angularjs web site:

// When defining a module with no module dependencies,
// the array of dependencies should be defined and empty.
var myApp = angular.module('myApp', []);

**Comment by hungdoan2** [comment]
@drmule there is an options : `standalone` to create a new module for you

**Comment by miickel** [comment]
Yeah, what @hungdoan2 said.
