### ISSUE TITLE
How to avoid redundant `\` before double quotes?

### ISSUE THREAD

**Issue by zhekaus** [miickel/gulp-angular-templatecache#120]
How to make it use single quotes instead of double ones and avoid redundant `\`?
It will shorten the code a little and instead of 
`$templateCache.put("zh-gap-rules.tpl.html","<div class=\"modal-header\">...`
we’ll get it without of `\`:
`$templateCache.put('zh-gap-rules.tpl.html','<div class="modal-header">...`

**Comment by miickel** [comment]
dup #93
