### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by sl0815** [miickel/gulp-angular-templatecache#127]
Hi,

I did a fresh npm install today and all of a sudden I'm getting this error:

> ENOENT:  no such file or directory, lstat '/Projects/Test/templates/templates.js'

Strange thing: My colleagues which did not a fresh npm install today, can still work with the exact same setup.

I can reproduce the error with this simple project setup.

```javascript
//gulpfile.js
(function() {
  "use strict";

  var gulp          = require('gulp');
  var templateCache = require('gulp-angular-templatecache');

  gulp.task('default', function() {
    return gulp.src('templates/**/*.html')
      .pipe(templateCache({module: 'test.templates', standalone: true}))
      .pipe(gulp.dest('dist/js'));
  });
})();
```
```javascript
// package.json
{
  "name": "test",
  "version": "1.0.0",
  "description": "Dummy project for bug reproduction",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "gulp": "^3.9.0",
    "gulp-angular-templatecache": "^1.8.0"
  },
  "dependencies": {
    "angular": "1.5.7"
  }
}

```
```html
<!-- templates/dummy.html -->
<h1>Test</h1>
```

I'm also able to reproduce this on Mac OS X 10.11.5 with node 6.2.0 (npm 3.8.9) and on Ubuntu 15.10 with node 5.6.0 (npm 3.6.0).

Any ideas on that?

**Comment by ARoddis** [comment]
I have the same problem on our buildsystem...it seems to install a different "version" of the same version of the package...in the "broken" one there is also a node_modules subfolder...

**Comment by chrissysemens** [comment]
2nd the above:
    gulp.task('cacheTemplates', function () {
        return gulp.src('app/**/*.html')
            .pipe(htmlmin({ collapseWhitespace: true }))
            .pipe(tCache('templates.js', {
                standalone: true,
                module: 'aa.templates',
                templateHeader: "(function(){'use strict';angular.module('aa.templates',[]).run(t);t.$inject=['$templateCache'];function t($templateCache){",
                templateFooter: "}})();",
                transformUrl: function (url) {
                    return url.replace(/\.view\.html$/, '.html');
                }
            }))
            .pipe(gulp.dest('build/temp/'));
    });

**Comment by chrissysemens** [comment]
Did you manage any workaround ARoddis? I'm suffering the same fate.

**Comment by ARoddis** [comment]
No im working on it at the moment. :) Ill keep you posted...

**Comment by KordonDev** [comment]
#124 try this fix

**Comment by sl0815** [comment]
I thinks this is a duplicate of https://github.com/miickel/gulp-angular-templatecache/issues/124.

The solution provided there fixed my problem.

**Comment by chrissysemens** [comment]
Thanks guys, I'm also poking. :)

**Comment by chrissysemens** [comment]
That's worked for me. Brilliant! Thank you.

**Comment by ARoddis** [comment]
Signed
