### ISSUE TITLE
String escaping doesnt appear to work in v2.0.0

### ISSUE THREAD

**Issue by aarondh** [miickel/gulp-angular-templatecache#131]
I'm getting the following in my templates file after upgrading to v2.0.0:

    templateCache.put("/scripts/app/components/admin/admin.html","<nav class="navbar navbar-default navbar-fixed-top inverse">\r\n    ...</div>\r\n</footer>");
Note that the quotes are not being escaped correctly.

**Comment by miickel** [comment]
Hi! Unfortunately I do not have time to take a look at this atm. I would welcome any PR on this issue though.

ping @paulhhowells

**Comment by paulhhowells** [comment]
@miickel @aarondh I will take a look

**Comment by paulhhowells** [comment]
@aarondh please could you provide some code samples:
the gulp code that runs gulp-angular-templatecache and the source html

**Comment by aarondh** [comment]
Looks like I was a little premature indicating a bug, the dev box in question did not have the latest node.js installed.  Once upgraded everything is now parsing correctly

**Comment by Karankang007** [comment]
I am still experiencing this issue in version 2.0.0. Is this fixed?

**Comment by paulhhowells** [comment]
@Karankang007  please could you provide some code samples:
* the gulp code that runs gulp-angular-templatecache
* the source html
* the other output from gulp-angular-templatecache around `templateCache.put()`
* version of npm

**Comment by Karankang007** [comment]
Gulp code: https://gist.github.com/Karankang007/fb2ed6434a1509ef9df169069b344744
Source HTML: https://gist.github.com/Karankang007/83096fa4393fe75d96a6d2034f94d156
Geneted Output: https://gist.github.com/Karankang007/2062aa80234f8a5e04511fede263672b

NPM Version: 3.10.3
Gulp Version: 3.9.1
