### ISSUE TITLE
When source empty create a empty js

### ISSUE THREAD

**Issue by warapitiya** [miickel/gulp-angular-templatecache#133]
When source is empty or null create a JS file at least with a empty angular module.

**Comment by pulasthibandara** [comment]
Please consider this. I get a no module found error if no template files are given. I know its a small issue, but its a real inconvenience :)

**Comment by simonua** [comment]
@warapitiya, @pulasthibandara, is this still relevant? If so, could you create a PR, please, and assign to each other, myself, and @miickel, please? If not, could you close the issue, please?

**Comment by simonua** [comment]
@pulasthibandara, thankl you. And very sorry for the very late reply.
