### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by SidharthPHariharan** [miickel/gulp-angular-templatecache#136]
Hi all I am unable to install this plugin and I get this following error in cli

npm WARN engine gulp-angular-templatecache@2.0.0: wanted: {"node":">=4.2.0"} (current: {"node":"0.12.7","npm":"2.11.3"})

This is the command I run
npm install -g gulp-angular-templatecache@1.9.1

Have someone else faced this issue? Please help me with this...

Thanks in advance.

**Comment by evestraw** [comment]
I had the same issue,  i havent found an solution

**Comment by marie-dk** [comment]
@SidharthPHariharan  If your node version is less than 4.2.0 (which yours clearly are) you must install version 1.9.1 of templatecache, or update node. The release of version 2 includes this info...
