### ISSUE TITLE
Angular Arguments

### ISSUE THREAD

**Issue by ToothlessRebel** [miickel/gulp-angular-templatecache#143]
`angular.module()` requires two argument as according to the [developer guide](https://docs.angularjs.org/guide/module). Currently the  `TEMPLATE_HEADER` variable only passes one.   
This is causing the module to **not** load. The following error reaches the console:  

> Uncaught Error: [$injector:nomod] Module 'templates' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

**Comment by miickel** [comment]
see the `standalone` option in README.
