### ISSUE TITLE
Remove deprecated gulp-util by updating gulp-header & gulp-footer

### ISSUE THREAD

**Issue by simonua** [miickel/gulp-angular-templatecache#150]
#149 in this repo recently removed its own immediate dependencies on gulp-util, but `npm ls gulp-util` shows remaining dependencies for [gulp-header](https://github.com/tracker1/gulp-header) and [gulp-footer](https://github.com/tracker1/gulp-footer). These dependencies were updated today to remove the deprecated [gulp-util](https://github.com/gulpjs/gulp-util), so we should update them here in order to rid _gulp-angular-templatecache_ of _gulp-util_ entirely.

**Comment by simonua** [comment]
Referencing the [gulp-util ecosystem migration ticket](https://github.com/gulpjs/gulp-util/issues/143).

**Comment by betorobson** [comment]
Hi, any update about this issue?

**Comment by tiberiuzuld** [comment]
+1
