### ISSUE TITLE
Security Issue: Removing dependency `event-stream`

### ISSUE THREAD

**Issue by TheSeg** [miickel/gulp-angular-templatecache#166]
[As noted in this issue](https://github.com/dominictarr/event-stream/issues/116), `event-stream` is compromised and the original maintainer doesn't have control over the repo.

I highly recommend removing `event-stream`, along with `gulp-footer` dependency (as mentioned in #150) which also contains `event-stream.

**Comment by simonua** [comment]
Thanks for opening this. Would you be willing to create a PR, please?

**Comment by simonua** [comment]
This is fixed now with v2.2.6.
