### ISSUE TITLE
Child module templateCache

### ISSUE THREAD

**Issue by corydorning** [miickel/gulp-angular-templatecache#38]
This is more of a question than an issue, but I was wondering how I can get this to work with child modules.

Most of my templates are referenced as follows via ui-router, and everything works as expected:

```
var app = angular.module('app', [
    'app.filters',
    'app.services',
    'app.controllers',
    'app.directives',
    'ngSanitize',
    'ngResource'
  ])
  .config(['$stateProvider', '$urlRouterProvider',
    function($stateProvider, $urlRouterProvider) {
      $stateProvider
        .state('page1', {
          url: '/page1',
          templateUrl: 'partials/page1.html'
         })

        .state('page2', {
          url: '/page2',
          templateUrl: 'partials/page2.html'
        })
    ...
  });
```

However, as you can see in the dependencies I inject above, I also have this:

```
angular.module('app.directives', [])
.directive('collapsible', function() {
    return {
        scope: {
            title: '@'
        },
        restrict: 'E',
        replace: true,
        transclude: true,
        templateUrl: 'partials/directives/collapsible.html',
        controller: function($scope) {
            $scope.collapsed = false;
            $scope.collapse = function() {
                $scope.collapsed = !$scope.collapsed;
            };
        }
    };
});
```

When running my app, I get the error `[$compile:tpload]` and the `GET` request to `partials/directives/collapsible.html` returns a 404, since it doesn't exist, obviously, since I want to use the `templateCache`.

I know what I'm getting the error, I'm just wondering how I can make `app.directives` aware of the `templateCache` for `app`. Gulp code is as follows:

```
// prod or test: create $templateCache
    gulp.src('partials/**/*.html')
      .pipe(ngCache({
          filename: 'partials.js',
          module: 'app'
        }))
      .pipe(gulp.dest('www'))
    ;
```

**Comment by Rleahy22** [comment]
I am having the same issue, and it was not resolved by setting a root. If I change the module in the templateCache options to the name of the submodule for the directive it works fine, but when it's the top level module it breaks.
