### ISSUE TITLE
Problem with gulp.src base option

### ISSUE THREAD

**Issue by lukescott** [miickel/gulp-angular-templatecache#42]
Given the following:

``` javascript
gulp.src(["src/**/*.html", "!src/index.html"], {base: "src"})
    .pipe(gulpif(condition, templateCache()))
        ...
    .pipe(gulp.dest("build"));
```

I end up with files like `/Users/lukescott/Documents/Projects/app/view/view.html`. Even though this appears to be a full path, this is wrong anyway. There is no "src" folder or "build" folder in this path. If I remove the base option it works fine. The problem is here:

https://github.com/miickel/gulp-angular-templatecache/blob/v1.4.0/index.js#L49

What's happening is it's simply replacing "src" with nothing. The correct approach, from what I can tell, is do something like this instead:

``` javascript
switch(typeof base) {
case 'function':
    url = path.join(root, base(file));
    break;
case 'string': // default?
    url = path.join(root, file.path.replace(base || file.base, ''));
case 'undefined':
    url = path.join(root, file.relative); // Should fix above case
default:
    // unknown type?
}
```

It seems that the `string` case could still be wrong because it's supposed to replace from the left side, not the middle, correct?

The workaround I have for now is this:

``` javascript
gulp.src(["src/**/*.html", "!src/index.html"], {base: "src"})
    .pipe(gulpif(condition, templateCache({base: function(file) {
            return file.relative;
        }})))
        ...
    .pipe(gulp.dest("build"));
```

**Comment by lukeed** [comment]
I know this has been closed, but it was still unresolved. I've solved it.

Using the `file.relative` path, you find the file's name after the last slash, and prepend your desired `base` string to it.

```javascript
  // ...
  .pipe(templateCache({
      // instead of this:
        // base: 'templates'
      // do this:
      base: function(file) {
        var filename = /[^/]*$/.exec( file.relative )[0];
        return 'templates/' + filename;
      }
    }))
  // ...
```
