### ISSUE TITLE
Way to build without templates.js file?

### ISSUE THREAD

**Issue by olsonpm** [miickel/gulp-angular-templatecache#54]
So I'm using angular + browserify and ideally this templates.js file would be completely transparent (meaning it only shows up in the browserify bundled js output).  The reason I say that would be ideal, is because it is essentially a build artifact, and thus should not be versioned.

What I would like to do is append the contents to the browserify entry file prior to bundling, but I'm new to all this and can't figure out whether that's even possible.

I would appreciate your thoughts on how to accomplish this if it is possible.

Thanks,
Phil

**Comment by Light241** [comment]
It works. I think you may add this to the readme
