### ISSUE TITLE
Modifying the path

### ISSUE THREAD

**Issue by willsoto** [miickel/gulp-angular-templatecache#55]
Currently, any path that contains `..` or `.` will be rewritten to omit those because `path.join()` and `path.normalize()` do this.

This is inconvenient when using RequireJS's [require.toUrl()](http://requirejs.org/docs/api.html#modulenotes-urls) as it will prepend `./` to the generated URLs (since require has to know where the file is). These are effectively the keys that are then used to look up the appropriate template by angular, hence the need to keep this path the way it is.

Do you have any suggestions for how to handle this? I have attempted using both the `base` and `root` options, but both of these get normalized.

If I were to submit a PR for this, I would probably add a hook to modify the url one last time before it is actually added to the template file, thereby avoiding the whole normalization problem. But I am not sure whether or not this is the path you'd like to take.

**Comment by leschirmeur** [comment]
I am having the same issue as paradox41.

However not using requirejs but the new angular router.
Need the ./ in the beginning but the join() method removes them.

Therefore requesting reopening this issue.

**Comment by paradox41** [comment]
I have a fork available with my fix that I have been using successfully for
quite some time. Feel free to check it out.

**Comment by leschirmeur** [comment]
@paradox41 Thank you, checked it out and this will work!

@miickel This should be added to this repo as well. By the way, thanks for this great module :-)
