### ISSUE TITLE
lodash.bind, Windows and long paths

### ISSUE THREAD

**Issue by johnnyreilly** [miickel/gulp-angular-templatecache#62]
Hi @miickel,

First up - thanks for the plug-in!

I don't know if you're aware of this but gulp-angular-templatecache can upset Visual Studio on Windows.  Once I installed it I started getting this message:

```
ASPNETCOMPILER : error ASPRUNTIME: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
```

This seems to be related to the long path issues discussed [here](https://github.com/joyent/node/issues/6960#issuecomment-46704998).  The workaround seems to be adding `lodash.bind` as a dev dependency to `packages.json`.  This way npm doesn't get the longer path underneath `gulp-angular-templatecache` in `node_modules`.  Thought I'd share it here since it burned a good portion of my time and I wanted to save anyone else the frustration I'd dealt with.

**Comment by jdalton** [comment]
Just a heads up. [lodash v3](https://github.com/lodash/lodash/releases/tag/3.0.0) has significantly reduced the dep graphs of its modularized packages. See [my comment](https://github.com/miickel/gulp-angular-templatecache/pull/63#issuecomment-74177290) over on #63.

**Comment by johnnyreilly** [comment]
:smile:
