### ISSUE TITLE
Problem minifying using gulp with ui-router?

### ISSUE THREAD

**Issue by therealbenhogan** [miickel/gulp-angular-templatecache#67]
Hi, 

When using a .config in ui-router such as 

.config(['$stateProvider','$urlRouterProvider','$locationProvider',function ($stateProvider,$urlRouterProvider,$locationProvider) {
etc etc
}]);

and a route defintion whereby "templateUrl" is replaced by eg 

templateProvider:function($templateCache) {
            return $templateCache.get('home.html');
 }

I can't minify the code using ugilify and concat. 

I've tried injecting $templateCache as a dependency in .config() but of course that doesnt work .... any ideas what to do to get this to work?

**Comment by theponti** [comment]
@therealbenhogan Are you using `ngannotate` or `ngmin` to minify your code? I had a similar issue and using `ngannotate` fixed it. 

Another way you can do this is to inject manually, which is a tip Igor from the Angular team uses sometimes throughout his code:

```js
function myTemplateProvider($templateCache) {
  return $templateCache.get('home.html');
}

myTemplateProvider.$inject = ['$templateCache'];

// Some code
   templateProvider: myTemplateProvider
// Some code
```

**Comment by therealbenhogan** [comment]
Hi, 

Am using gulp-concat and uglify

This looks great - many thanks. I have lots of (route) states to deal with - can you advise me how I would use this technique under these circumstances

Many thanks

**Comment by theponti** [comment]
@therealbenhogan I'm not entirely sure what you mean. I'm assuming you're using `angular-ui-router` and you shouldn't need to use $templateCache to resolve templates in the cache because it checks the cache first before decided to launch an HTTP request.

**Comment by therealbenhogan** [comment]
Sorry - are you saying I don't need to use 

 templateProvider:function($templateCache) {
     return $templateCache.get('page-home.html');
  }

and I can just use 'templateUrl:'page/page-home.html'

eg 

  $stateProvider
    .state('home', {
      url: '/page/index',
      views:{
        '':{
           templateUrl:'page/page-home.html' OR 
            templateProvider:function($templateCache) {
            return $templateCache.get('page-home.html');
          }
        },
      }
    })

**Comment by theponti** [comment]
Yes, exactly. You can use the `templateUrl` syntax as so:

```js
$stateProvider
  .state('home', {
    url: '/page/index',
    views: {
      '': {
        templateUrl:'page/page-home.html'
      }
    }
  });
```

Also, it's convention not to use a `index` in the URI, as it is assumed that the `/page` route would be the index view for that state.

**Comment by therealbenhogan** [comment]
Hi, 

Many thanks for confirming and letting me know on this! Re the route, I'll remove index going forward.
