### ISSUE TITLE
Path for template files being removed

### ISSUE THREAD

**Issue by prettycode** [miickel/gulp-angular-templatecache#72]
Let's say I have this in my gulp file:

    var paths = [ 
        'Scripts/app/components/chart/chart.tpl.html',
        'Scripts/app/factories/httpErrorInterceptor/httpErrorInterceptor.tpl.html'
    ];

    gulp.src(paths)
        .pipe(angularTemplatecache({ standalone: true }))

The output I get is:

    angular.module("templates", []).run(["$templateCache", function($templateCache) {$templateCache.put("chart.tpl.html", ...
    $templateCache.put("httpErrorInterceptor.tpl.html","...

Am I correct in thinking that there's no way to get this output below instead?

    angular.module("templates", []).run(["$templateCache", function($templateCache) {$templateCache.put("Scripts/app/components/chart/chart.tpl.html", ...
    $templateCache.put("Scripts/app/factories/httpErrorInterceptor.tpl.html","...

I don't understand why the path should be shaved off. What if I want to keep them (as I do)?

Looking in `index.js` of the `master` source, on line 49, I see that the original file path is being stripped via `file.path.replace(base || file.base, '')`. Why do this? `gulp-templatecache` doesn't do this&mdash;you have to explicitly tell it to strip out part of the path if you want it removed.

**Comment by prettycode** [comment]
I can use `base` argument as a function.

**Comment by prettycode** [comment]
I can use `base` argument as a function.

**Comment by bigmeech** [comment]
@prettycode hi could you please provide some sample code on how you solved this issue. I'm having the same.

**Comment by prettycode** [comment]
@bigmeech for me, on Windows, this is what did the trick: 

    var templateRootDir = __dirname,
        templateOptions = {
            root: '/',
            base: function (file) {
                return file.path.replace(templateRootDir, '').replace(/\\/g, '/');
            }
        };
        
    ...
    angularTemplatecache(templateOptions)
    ...

Hope this helps!

**Comment by tinyfly** [comment]
Thanks @prettycode This was driving me crazy.

In my case setting `base: process.cwd()` worked great for me since the gulpfile is in the root of the repo.

**Comment by bennekrouf** [comment]
@tinyfly +1
