### ISSUE TITLE
Angular requires error / injection error

### ISSUE THREAD

**Issue by NightkingCH** [miickel/gulp-angular-templatecache#76]
Hi there!

I'm using angular v1.4.0-beta.6 and running into this error:

Uncaught Error: [$injector:nomod] Module 'templates' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

So your plugin misses an empty array for the module registration:

angular.module("templates") => angular.module("templates". []).run([...]);

When I add an empty array manually it works and angular fetches the html templates as planned.

Is this an angular beta bug? Is it possible for you to fix this without screwing something else up?  => I don't know the earlier module registration process by angular :).

Thanks in advance!

**Comment by willpracht** [comment]
So, what you're likely running into is this:

When you're developing, it's likely you're not running this plugin, thus the 'templates' module won't be created.

To get around this, you can either do as you did by creating an empty module placeholder or update your config to add your templates to an existing module (like your root app module).

**Comment by miickel** [comment]
Hi! Take a look at `options.standalone` in README or #57
