### ISSUE TITLE
perhaps you move the filename specification into option?

### ISSUE THREAD

**Issue by e-cloud** [miickel/gulp-angular-templatecache#77]
it strange that if i want to specify some option that i should **specify the filename** first which i want to use the default~~. i think it's better that specify the filename in the option object if you need. it's more convenient and clean!

**Comment by miickel** [comment]
You _can_ set the filename using `options.filename`, or leave it out and set other options if you'd like.

**Comment by e-cloud** [comment]
oh, i'm so sorry. i just check the source. `filename` can be turn into `option` if `filename` is not **string**. but i did not see that `filename` is an optional param in README. it would be great to notify others who want to use this package.
