### ISSUE TITLE
Add ability to use regexes

### ISSUE THREAD

**Issue by stramel** [miickel/gulp-angular-templatecache#81]
I think it would add a lot of functionality to this plugin to allow config options like:

* `stripPrefix` - allows you to specify a string/regex to strip from the url
* `stripSuffix` - allows you to specify a string/regex to strip from the url

This idea is pulled directly from karma's preprocessor nghtml2js

**Comment by stramel** [comment]
Switched to `gulp-ngHtml2js` instead since it already has most of the features I was wanting.

**Comment by stramel** [comment]
I guess I am going to reopen this since Gulp 4 has `gulp-ngHtml2js` blacklisted as a duplicate of this package. So I would love to see this feature added to this package.

**Comment by miickel** [comment]
Hello! The next release will include a `transformUrl` option which you can use to massage the url to whatever you'd like. see #79
