### ISSUE TITLE
Continuous compilation of template file

### ISSUE THREAD

**Issue by trevorhreed** [miickel/gulp-angular-templatecache#85]
It would be fantastic if this plugin support functionality similar to [gulp-continuous-concat](https://www.npmjs.com/package/gulp-continuous-concat). I would like to be able to update the template cache file piecemeal, so that compilation remains fast even when there are many, large templates to be compiled. Even if my template files are few and small, I would need this plugin to support this continuous concatenation functionality in order to be able to compile my JavaScript piecemeal without having to write the templates.js file out to disk.

**Comment by miickel** [comment]
sure, I would welcome any pull requests to support this.

**Comment by trevorhreed** [comment]
I finally got around to spending some time on this. However, the changes I ended up making are substantial enough that I'm uncertain if it would be better to try to integrate them into this repo or start a new repo entirely. Do you have any strong feelings one way or another?
