### ISSUE TITLE
path.relative

### ISSUE THREAD

**Issue by MartyIX** [miickel/gulp-angular-templatecache#87]
Hi,

it might be a good idea to use `path.realtive(base, file.path)` (https://nodejs.org/api/path.html#path_path_relative_from_to) for path resolution here: https://github.com/miickel/gulp-angular-templatecache/blob/master/index.js#L58

It makes the script more robust. Especially when base path is written like this: 

    var base = "<something>" + '/public/script'  // this will fail on Windows

Have a nice day!

**Comment by miickel** [comment]
Using path.relative will change the behaviour of the option. Run the tests using path.relative and they will fail.

**Comment by MartyIX** [comment]
Thank you for the reply.
