### ISSUE TITLE
Separate module per template partial

### ISSUE THREAD

**Issue by stramel** [miickel/gulp-angular-templatecache#89]
I would love to have the same ability that `ngHtml2js` does where you can create a module for each template file.

**Comment by miickel** [comment]
Ok, help me out here... what's the point in doing that? For me it would just mean more work, by having to "require" a new module for each template, right? I see no benefit for it, but I leave it here for the community to discuss!

**Comment by AnimaMundi** [comment]
Maybe the ability to modularize multiple partials together would be nice, and it could have implications for selectively caching modules for different sections of a very large website but the work involved in implementing that as well as configuring it on a per website basis would be impractical.

**Comment by miickel** [comment]
@AnimaMundi that's true, but you could still just set up separate gulp tasks to achieve the same thing. Just have templates from module A in folder A, and module B in folder B and you're good to load them separately.

**Comment by AnimaMundi** [comment]
I guess that answers @stramel question too then!!! I didn't realise you could specify a module title until after I commented I only came across this plugin this morning. I have gone from building sites with a php framework with 2,899 files to around 5 files with javascript, it's insane. Good work on this contribution!

**Comment by AnimaMundi** [comment]
Never mind, the node_modules folder has 12,000 files.... ah well haha
