### ISSUE TITLE
transformUrl not working?

### ISSUE THREAD

**Issue by ehorodyski** [miickel/gulp-angular-templatecache#90]
Sorry to post such a simple question, but I want to make sure I'm writing my statement correctly. What I'm trying to do is append a timestamp to each .html file being put into the template cache, to try to cachebust it on the fly since our `templateCache` task is being watched for changes and recompiles as we edit HTML files. 

This is how I'm approaching the statement (I'm using `gulp-util` so that's why the module name looks funny:

`.pipe($.angularTemplatecache('templates.js', { transformUrl: function (url) { return url + '?' + date.toJSON(); } }))`

Along with the full task:

    gulp.task('template', function() {
	
	    var date = new Date();
	    return gulp.src(config.dir.ngDev + '**/*.html')
		    .pipe($.plumber({ errorHandler: onError }))
		    .pipe($.angularTemplatecache('templates.js', { transformUrl: function (url) { return url + '?' + date.toJSON(); } }))
		    .pipe(gulp.dest(dest.ngCompiled));
	
    });

**Comment by vigie** [comment]
I have very similar looking code and for me too it seems transformUrl is ignored.

**Comment by vigie** [comment]
Looks like a typo in code/API docs. It's not transformUrl it's transformurl:

https://github.com/miickel/gulp-angular-templatecache/blob/master/index.js#L67

**Comment by miickel** [comment]
@ehorodyski did updating solve your problems with transformUrl?

**Comment by elgervb** [comment]
Got the same issue, but it was resolved when updating ;-)

**Comment by miickel** [comment]
cool, I'll close this now. thanks all
