### ISSUE TITLE
Option to select quote (single vs double)

### ISSUE THREAD

**Issue by xgvargas** [miickel/gulp-angular-templatecache#93]
Hi, first let me say it's a great package, it is working very well in here.

As a suggestion for a new feature I would say you could give, as an options, a chance to select which quote you will use to pack template content as string. Usually HTML has lots of " and you have to escape each of them. In my case I count more then 2k lost in \ for escaping only. If you use a single quote to define the string we can afford almost all (you still have to escape single quote, but it is not so common as double), of these escaping, right? or am I missing something?

**Comment by johannesjo** [comment]
+1

**Comment by jonathan-reisdorf** [comment]
+1

**Comment by willpracht** [comment]
You can use the `template*` options to switch the template to using single quotes if you'd like.

It would be kind of cool to not have to do that, however, and just pass in a `quotes` option instead, maybe. Especially if that's the only thing you need to alter within the templates.

**Comment by jonathan-reisdorf** [comment]
@willpracht What you are proposing basically works but won't stop double quotes from being escaped, which would actually be the desired behavior.
so, doing a
```
templateBody : "$templateCache.put('<%= url %>', '<%= contents %>');"
```

will result in sth like this

```
$templateCache.put('path/to/template.html', '<span class=\"whatever\"></span>');
```
with double quotes still being escaped

**Comment by willpracht** [comment]
Ah, yes.

I definitely like your suggestion then, to pass in a quotes config option. :)

**Comment by miickel** [comment]
Yeah, this would be a nice addition to the plugin. We currently use the [js-string-escape](https://github.com/joliss/js-string-escape)-module to escape the template content, so optimally the option would have to be implemented there as well.

I have no time to add this functionality atm, but I would welcome any pull requests (please include tests as well).

**Comment by brentoneill** [comment]
+1

**Comment by paulhhowells** [comment]
@miickel to respond to the good point you made, and hopefully help the conversation keep moving forward, I have forked:
https://github.com/paulhhowells/gulp-angular-templatecache/
https://github.com/paulhhowells/js-string-escape

I thought you might have comments before I opened a pull request, and there might not be much point unless js-string-escape was merged first.

What do you think?

N.B.: My addition to js-string-escape is a bit belt & braces and probably ought to be more elegant, and I still need to add tests to gulp-angular-templatecache.

**Comment by paulhhowells** [comment]
@mathiasbynens got in touch to suggest that alternatively it might be worth considering use of the quotes option in jsec:
https://github.com/mathiasbynens/jsesc#quotes

**Comment by mathiasbynens** [comment]
Sorry, I meant the `wrap` option, not `quotes`. https://github.com/mathiasbynens/jsesc#wrap

**Comment by paulhhowells** [comment]
@miickel would you be open to a pull request (with tests) that resolved this issue and replaced js-string-escape with jsesc?

**Comment by miickel** [comment]
@paulhhowells yes, absolutely.

**Comment by paulhhowells** [comment]
Hi @mathiasbynens,
We need
`<h1 id="template-b">I'm template A!</h1>`
to become
`<h1 id="template-b">I\'m template A!</h1>`
so that it may be used in a string wrapped by single quotes.

However when using the default setting of `{ 'quotes' : 'single' }`
1) jsec does not escape unescaped single quotes
2) jsec does not remove escaping from double quotes

Am I missing a setting in jsec which would perform this? 
Or would you be open to adding this functionality to jsec?

Thanks,
Paul

**Comment by mathiasbynens** [comment]
@paulhhowells 

> 1) jsec does not escape unescaped single quotes

What makes you say this? What are you doing exactly? Can you provide a test case? It works for me.

```js
var string = '<h1 id="template-b">I\'m template A!</h1>';
jsesc(string, { quotes: 'single' });
// → '<h1 id="template-b">I\'m template A!</h1>'

// Note: `quotes: 'single'` is the default setting, so you can omit it.
jsesc(string);
// → '<h1 id="template-b">I\'m template A!</h1>'
```

**Comment by paulhhowells** [comment]
@mathiasbynens 
```js
var string = '';

// string wrapped in single quotes
string += '<h1 id="template-b">'; 

// an unescaped single quote in a string wrapped in double quotes
string += "I'm template A!</h1>";

jsesc(string);
// → <h1 id="template-b">I'm template A!</h1>
```

whereas we need
```js
// → <h1 id="template-b">I\'m template A!</h1>
```

**Comment by mathiasbynens** [comment]
The string from your example is equivalent to `'<h1 id="template-b">I\'m template A!</h1>'`.

```js
string == '<h1 id="template-b">I\'m template A!</h1>'
// → true
```

And `jsesc(string)` is then:

```js
jsesc(string)
// → '<h1 id="template-b">I\\'m template A!</h1>'

Where/how are you testing this? I wonder what makes you not see the `\`.

**Comment by paulhhowells** [comment]
@mathiasbynens 
I’ve rebuilt my test, and I can see the '\' now.   Sigh…
Human error I’m afraid, I apologise for any strife caused.

Paul

**Comment by mathiasbynens** [comment]
No worries :)

**Comment by paulhhowells** [comment]
@miickel 
https://github.com/paulhhowells/gulp-angular-templatecache passes all the mocha tests and no longer escapes double quotes in the HTML that don’t need to be escaped.  Caveat: I need to sleep on this, and double check the code. ;-)

Rather than create an option (as the creator of this issue suggested) I have simply changed the default behaviour (because I cannot think of a reason you would want unnecessary escaping, and because I’m lazy :-p).

If you’d prefer this behaviour to be enabled by an optional setting instead of being the default please let me know and I will take a look.

If on the other hand you are happy with what you see, please let me know and I will open a pull request.

**Comment by paulhhowells** [comment]
@miickel is there anything I can do to make it easier for you to merge the pull request?
