### ISSUE TITLE
Option to alias urls

### ISSUE THREAD

**Issue by jacksonrayhamilton** [miickel/gulp-angular-templatecache#96]
It's possible for a programmer to accidentally specify an absolute path when he intends to specify a relative path:

`templateUrl: '/common/foo/foo-directive.html'`

vs

`templateUrl: 'common/foo/foo-directive.html'`

On a local development server, he might accidentally be able to resolve that url via angular's default behavior of sending an HTTP request there, but on production that path might not exist anymore. This can lead to hard-to-debug errors.

Ideally we'd always specify relative paths, but programmers make mistakes. So, I'd like an option to alias urls, such that the generated templateCache code for that url would be:

``` js
["common/foo/foo-directive.html","/common/foo/foo-directive.html"].forEach(function(u){$templateCache.put(u,"<div class=\"foo\"></div>")})
```

**Comment by miickel** [comment]
I think this is a programmer's error, and should not be encouraged. Besides, I don't find it that hard to debug. However I'll leave the issue open a bit longer to see if someone else might be interested in this (PR welcome, in that case).

**Comment by trevorhreed** [comment]
I think you could take advantage of the transformUrl option to ensure that all paths are relative:

```js
gulpAngularTemplateCache({
    'transformUrl': function(url) {
        if(url.indexOf('/') === 0) url = url.substr(1);
        return url;
    }
});
```
