### ISSUE TITLE
New gulp-header version introduces an error

### ISSUE THREAD

**Issue by mjwwit** [miickel/gulp-angular-templatecache#99]
The new 1.5.0 release of gulp-header introduced an [issue](https://github.com/tracker1/gulp-header/issues/21). Because of this issue, gulp-angular-templatecache is now no longer working.

This is mostly gulp-header's problem, but maybe you can update your dependency versions to only auto-update patches.

`"gulp-header": "~1.4.0"` instead of `"gulp-header": "1.x"` would have prevented this issue.

Can you tighten your dependency versions so these bugs can be prevented in the future?

**Comment by miickel** [comment]
duplicate #97
